name: Fork new repositories
on:
  workflow_dispatch
  #schedule:
  # - cron: '0 3 * * *'
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          repos=$(curl https://ktane.timwi.de/json/raw | jq ".KtaneModules[].SourceUrl | select( . != null)" | sed 's#"https://github.com/\(.*\)"#\1#')
          for repo in $repos; do
            echo "Forking $repo"
            json=$(jq -n --arg name "$repo" '{"organization":"KTaNE-noi2coco", "name": $name, "default_branch_only": false}')
            curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${repo}/forks \
              -d "$json"
            exit 0
          done
          
