name: Fork new repositories
on:
  workflow_dispatch
  #schedule:
  # - cron: '0 3 * * *'
jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - env:
          TOKEN: ${{ secrets.TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS: ${{ vars.REPOS }}
        run: |
          function isforked {
            echo "Checking if $1 is already forked"
            # check if the current $repo has already been forked
            case "$REPOS" in 
              *"$1"*)
                echo "Fork found, skipping"
                return 0
              ;;
            esac
            echo "No fork found for $1"
            return 1
          }

          function fork {
            ret=$(curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              $1/forks \
              -d "$2")
            REPOS="$REPOS;$3"
            echo "$ret"
          }

          # get source code links from ktane.timwi.de
          repos=$(curl https://ktane.timwi.de/json/raw | jq -r ".KtaneModules[].SourceUrl | select( . != null)" | cut -d/ -f4-5)
          # get list of forked repositories
          
          for repo in $repos; do
            forkname=$(echo "$repo" | sed 's#/#-#g')
            if isforked "$forkname"; then
              continue
            fi
            
            # Fork the new repository
            json=$(jq -n --arg name "$repo" '{"organization":"KTaNE-noi2coco", "name": $name, "default_branch_only": false}')
            echo "Forking $repo" as "$repo"
            out=$(fork https://api.github.com/repos/${repo} "$json" "$repo")
            echo "out = $out"

            # Repo moved?
            message=$(jq -r ".message" <<< "$out")
            echo "Message: $message"
            if [ "$message" = "Not Found" ]; then
              getrepo=$(gh api -H "Accept: application/vnd.github+json" /repos/${repo})
              url=$(jq -r ".url" <<< "$getrepo")
              echo "Get repo answer: $url"
              if [ "$url" != "null" ]; then
                echo "Forking $url as $repo, payload: $json"
                out=$(fork "$url" "$json" "$repo")
                message=$(jq -r ".message" <<< "$out")
                if [ "$message" = "Name already exists on this account" ]; then
                  ##!!!
                  echo "$repo alreay exists"
                  break
                  continue
                fi
              fi
            fi
            sleep 3
            ##!!!
            break
          done
          
          # Update the list of forks repository variable
          payload=$(jq -n --arg repos "$REPOS" '{"name":"REPOS","value": $repos}')
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/KTaNE-noi2coco/repository-scrapper/actions/variables/REPOS \
            -d "$payload"
