name: Fork new repositories
on:
  workflow_dispatch
  #schedule:
  # - cron: '0 3 * * *'
jobs:
  use_api:
    runs-on: ubuntu-latest
    steps:
      - env:
          TOKEN: ${{ secrets.TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          function isforked {
            for repo in $1; do
              # check if the current $repo has already been forked
              for fork in $forks; do
                if [ "$2" = "$fork" ]; then
                  return 0
                fi
              done
            done
            return 1
          }

          function fork {
            curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              $1 \
              -d "$2"
          }

          # get source code links from ktane.timwi.de
          repos=$(curl https://ktane.timwi.de/json/raw | jq -r ".KtaneModules[].SourceUrl | select( . != null)" | cut -d/ -f4-5)
          # get list of forked repositories
          forks=$(gh api \
            -H "Accept: application/vnd.github+json" \
           /orgs/KTaNE-noi2coco/repos | jq -r '.[].name')

          for repo in $repos; do
            forkname=$(echo "$repo" | sed 's#/#-#g')
            if isforked "$forks" "$forkname"; then
              continue
            fi
            
            # Fork the new repository
            json=$(jq -n --arg name "$repo" '{"organization":"KTaNE-noi2coco", "name": $name, "default_branch_only": false}')
            echo "Forking $repo" as "$json"
            out=fork https://api.github.com/repos/${repo}/forks "$json"
            
            # Repo moved?
            message=$(jq -r ".message" <<< "$out")
            echo "Message: $message"
            if [ "$message" = "Not Found" ]; then
              getrepo=$(gh api -H "Accept: application/vnd.github+json" /repos/${repo})
              message=$(jq ".message" <<< "$getrepo") 
              if [ "$message" = "Moved Permanently" ]; then
                url=$(jq -r ".url" <<< "$getrepo")
                echo "Forking $url" as "$json"
                fork "$url" "$json"
              fi
            fi
            sleep 5
          done
