name: Fork new repositories
on:
  workflow_dispatch
  #schedule:
  # - cron: '0 3 * * *'
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          # get source code links from ktane.timwi.de
          repos=$(curl https://ktane.timwi.de/json/raw | jq -r ".KtaneModules[].SourceUrl | select( . != null)" | cut -d/ -f4-)
          # get list of forked repositories
          forks=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /orgs/KTaNE-noi2coco/repos | jq -r '.[].name') 

          for repo in $repos; do
            # check if the current $repo has already been forked
            forked=0
            forkname=$(echo "$repo" | sed 's#/#-#g')
            for fork in $forks; do
              if [ "$forkname" = "$fork" ]; then
                forked=1
                break
              fi
            done
            if [ $forked -eq 1 ]; then
              continue
            fi
            
            # Fork the new repository
            echo "Forking $repo"
            json=$(jq -n --arg name "$repo" '{"organization":"KTaNE-noi2coco", "name": $name, "default_branch_only": false}')
            curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${repo}/forks \
              -d "$json"
            sleep 5
          done
