name: Synchronize forks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
jobs:
  sync_forks:
    runs-on: ubuntu-latest
    steps:
      - env:
          TOKEN: ${{ secrets.TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS: ${{ vars.REPOS }}
        run: |
          IFS=';' read -ra repos <<< "$REPOS"
          for repo in "${repos[@]:1}"; do
            # get default branch name
            getrepo=$(gh api -H "Accept: application/vnd.github+json" /repos/KTaNE-noi2coco/$repo)
            echo "getrepo= $getrepo"
            message=$(jq -r ".message" <<< "$getrepo")
            [ "message" = "Not Found" ] && continue
            default_branch=$(jq -r ".default_branch" <<< "$getrepo")
            echo "default branch: $default_branch'

            # synchronize the fork with upstream
            payload=$(jq --arg branch "$default_branch" <<< '{"branch": $branch}')
            echo "payload=$payload"
            curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/KTaNE-noi2coco/REPO/merge-upstream \
              -d "$payload"

            sleep 5
          done
