name: Synchronize forks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
jobs:
  sync_forks:
    runs-on: ubuntu-latest
    steps:
      - env:
          TOKEN: ${{ secrets.TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOS: ${{ vars.REPOS }}
        run: |
          for repo in $REPOS; do
            # get default branch name
            default_branch=$(gh api
                              -H "Accept: application/vnd.github+json"
                              -H "X-GitHub-Api-Version: 2022-11-28"
                              /repos/KTaNE-noi2coco/$repo | jq -r ".default_branch")

            # synchronize the fork with upstream
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/KTaNE-noi2coco/$repo/merge-upstream \
              -f branch="$default_branch"

            sleep 5
          done
